approvedGitRepositories:
  - "**"

catalog:
  chalk: 5.2.0
  debug: 4.3.0

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

yarnPath: .yarn/releases/yarn-4.17.1.cjs
