[package]
name = "sample-rust"
version = "1.0.0"
edition = "2021"
description = "Sample Rust project with postcard-cobs and wasi bindings."
authors = ["Naresh Kumar <Naresh_Kumar@lineaje.com>"]

[dependencies]
postcard-cobs = "0.1.5-pre"
wasi = "0.10.2+wasi-snapshot-preview1"
wasi-v0_11 = { package = "wasi", version = "0.11.1+wasi-snapshot-preview1" }
